#!/bin/bash -e

eval "$(cli-shezargs $@)"

[[ -n $verbose        ]] && ava_verbose="--verbose"
[[ -n $main_color     ]] && export TEST_MAINCOLOR="$main_color"
[[ -n $next_color     ]] && export TEST_NEXTCOLOR="$next_color"
[[ -n $stack          ]] && export TEST_STACK="$stack"
[[ -n $hq_subdomain   ]] && export TEST_HQSUBDOMAIN="$hq_subdomain"
[[ -n $xapi_subdomain ]] && export TEST_XAPISUBDOMAIN="$xapi_subdomain"

ava ${ava_verbose} systemtest/test-stack-routing.js

