#!/bin/bash -e

eval "$(cli-shezargs $@)"

[[ -n $verbose        ]] && ava_verbose="--verbose"
[[ -n $main_color   ]] && export TEST_MAINCOLOR="$main_color"
[[ -n $next_color   ]] && export TEST_NEXTCOLOR="$next_color"
[[ -n $product      ]] && export TEST_PRODUCT="$product"
[[ -n $service      ]] && export TEST_SERVICE="$service"
[[ -n $stack        ]] && export TEST_STACK="$stack"

ava ${ava_verbose} systemtest/test-product-routing.js

