#!/bin/bash -e

eval "$(cli-shezargs $@)"

[[ -z $ip   ]] && die "Need --ip="
[[ -z $fqdn ]] && die "Need --fqdn="

# ----- Nessus agent
if [[ $stack == prod ]]; then
  sshix $ip "cd ~/dev/bridge47/admin/build/on-instance/ && ./zz2-extra"
fi

# ----- no-domain
curl -sS "http://$ip:12340/file/etc/nginx/nginx.conf" | egrep '# CONFIG_JSON ' | sed 's/^[^{[]*//g' > /tmp/config.json
sshix $ip "cd ~/dev/bridge47/bridge47-plugins/no-domain/ && pm2 start no-domain.js -- port=$(cat /tmp/config.json | jq -r '.routerPort')"

if [[ -n $client_certs ]]; then
  curl -sS "http://$ip:12340/file/etc/nginx/sites-enabled/${fqdn}.conf" | egrep '# CONFIG_JSON ' | sed 's/^[^{[]*//g' > /tmp/config.json
  sshix $ip "cd ~/dev/bridge47/bridge47-plugins/xapi && pm2 start xapi-router.js --name xapi -- --port=$(cat /tmp/config.json | jq -r '.routerPort')"
fi

# ----------- start nginx ----------
sshix $ip "sudo nginx -t && sudo nginx"

