#!/bin/bash -e

#
# Runs an hq instance.
#
#   * Configs nginx with fqdns: console.mobilewebasist.net; xapi.mwp.net; and hq.mwp.net
#
# Note: Regarding fqdns:
#   * it might be mobilewebassist.net or mobiledevassist.net, depending on prod/non-prod.
#   * it might be 'console' or 'b47console' (the same for xapi and hq).
#
*   * hq is https
#   * xapi and console require https and client-side certs
#    * however, currently, xapi does not require client-side certs
#

# Defaults
stack="cluster"
domain_name="mobiledevassist.net"

sconfig_client="&client_certs=1"
sconfig_https="&https=1"

hq_subd="b47hq"
xapi_subd="b47xapi"
console_subd="b47console"

# Process cli args
eval "$(cli-shezargs $@)"

ns="$NAMESPACE"

[[ -z $ns     ]] && die "Need --namespace="
[[ -z $color  ]] && die "Need --color="
[[ -z $stack  ]] && die "Need --stack="

if [[ $stack == prod ]]; then
  assumed_acct="pub"
  domain_name="mobilewebassist.net"
fi

${scripts_dir}/launch/run-instance --stack=${stack} --tier=web --color=${color} "$@"

ip="$(cat /tmp/run-instance-result.json | jq -r '.Instances[].PrivateIpAddress')"
instance_id="$(cat /tmp/run-instance-result.json | jq -r '.Instances[].InstanceId')"

${scripts_dir}/aws-assumed-role "$assumed_acct" ec2 create-tags --resources "$instance_id" --tags "Key=color,Value=$color" "Key=stack,Value=${stack}"

# ---------- Configure nginx ----------

# Setup for the following FQDNs
curl -sS "http://$ip:12340/root-config"
curl -sS "http://$ip:12340/server-config?fqdn=${console_subd}.${domain_name}&port=5778${sconfig_client}${sconfig_https}"
#curl -sS "http://$ip:12340/server-config?fqdn=${xapi_subd}.${domain_name}&port=5778${sconfig_client}${sconfig_https}"
curl -sS "http://$ip:12340/server-config?fqdn=${xapi_subd}.${domain_name}&port=5778&http=1"
curl -sS "http://$ip:12340/server-config?fqdn=${hq_subd}.${domain_name}&port=5777${sconfig_https}"

# ---------- Get the nginx conf files ----------

# =======================================================================
# And push the needed certs
announce "Pushing certs to server"
# =======================================================================

# ----- b47console.mobilewebassist.net
curl -sS "http://$ip:12340/file/etc/nginx/sites-enabled/${console_subd}.${domain_name}.conf" | egrep '# CONFIG_JSON ' | sed 's/^[^{[]*//g' > /tmp/config.json

push-cert-to-server "ssh_cert"      "$(cat /tmp/config.json | jq -r '.certfile')" "$ip"
push-cert-to-server "ssh_key"       "$(cat /tmp/config.json | jq -r '.keyfile')" "$ip"
push-cert-to-server "client_cert"   "$(cat /tmp/config.json | jq -r '.clientCert')" "$ip"



# ----- b47hq.mobilewebassist.net
curl -sS "http://$ip:12340/file/etc/nginx/sites-enabled/${hq_subd}.${domain_name}.conf" | egrep '# CONFIG_JSON ' | sed 's/^[^{[]*//g' > /tmp/config.json

push-cert-to-server "ssh_cert"      "$(cat /tmp/config.json | jq -r '.certfile')" "$ip"
push-cert-to-server "ssh_key"       "$(cat /tmp/config.json | jq -r '.keyfile')" "$ip"
push-cert-to-server "client_cert"   "$(cat /tmp/config.json | jq -r '.clientCert')" "$ip"


# Only start the server if the caller wants
if [[ -z $delay_finishing ]]; then

  [[ -n ${hq_subd}        ]] && extra_args="${extra_args} --hq-subd=${hq_subd}"
  [[ -n ${xapi_subd}      ]] && extra_args="${extra_args} --xapi-subd=${xapi_subd}"
  [[ -n ${console_subd}   ]] && extra_args="${extra_args} --console-subd=${console_subd}"

  ${scripts_dir}/run-final-hq-start-tasks --ip=${ip} --stack=${stack} ${extra_args}
fi

