#!/bin/bash -e

#
# Finalize work for an app instance:
#
# 1. Run xapi router
# 2. Start nginx
#

eval "$(cli-shezargs $@)"

[[ -z $ip   ]] && die "Need --ip="

# ----- Nessus agent
env
echo "=================================== Run nessus? $stack"
if [[ $stack == prod ]]; then
  echo "running nessus"
  sshix $ip "cd ~/dev/bridge47/admin/build/on-instance/ && ./zz2-extra"
fi

# ----- no-domain
curl -sS "http://$ip:12340/file/etc/nginx/nginx.conf" | egrep '# CONFIG_JSON ' | sed 's/^[^{[]*//g' > /tmp/config.json
sshix $ip "cd ~/dev/bridge47/bridge47-plugins/xapi && pm2 start xapi-router.js --name xapi -- --port=$(cat /tmp/config.json | jq -r '.routerPort')"




# Note: This is what you would do if the internal instance were to be addressable via name through nginx

#curl -sS "http://$ip:12340/file/etc/nginx/sites-enabled/${color}-test.mobiledevassist.net.conf" | egrep '# CONFIG_JSON ' | sed 's/^[^{[]*//g' > /tmp/config.json
#sshix $ip "cd ~/dev/bridge47/bridge47-plugins/xapi && pm2 start xapi-router.js --name xapi -- --port=$(cat /tmp/config.json | jq -r '.routerPort')"


# ----------- start nginx ----------
sshix $ip "sudo nginx -t && sudo nginx"


