#!/bin/bash -e

#
# The final step is to startup the right services on the instance.
#
# * Nessus agent
#
# * pm2 start various handlers:
#  * no-domain
#  * xapi
#  * clientStart
#
# * nginx
#

domain_name="mobiledevassist.net"
hq_subd="b47hq"
xapi_subd="b47xapi"
console_subd="b47console"

eval "$(cli-shezargs $@)"

[[ -z $ip       ]] && die "Need --ip="
[[ -z $stack    ]] && die "Need --stack="

if [[ $stack == prod ]]; then
  domain_name="mobilewebassist.net"
fi

# ----- Nessus agent
if [[ $stack == prod ]]; then
  sshix $ip "cd ~/dev/bridge47/admin/build/on-instance/ && ./zz2-extra"
fi

# ----- no-domain
curl -sS "http://$ip:12340/file/etc/nginx/nginx.conf" | egrep '# CONFIG_JSON ' | sed 's/^[^{[]*//g' > /tmp/config.json
sshix $ip "cd ~/dev/bridge47/bridge47-plugins/no-domain/ && pm2 start no-domain.js -- --port=$(cat /tmp/config.json | jq -r '.routerPort')"

# ----- b47console.mobilesebassist.net
# Note: b47console is handled by the same handler as b47xapi

# ----- b47xapi.mobilesebassist.net
curl -sS "http://$ip:12340/file/etc/nginx/sites-enabled/${xapi_subd}.${domain_name}.conf" | egrep '# CONFIG_JSON ' | sed 's/^[^{[]*//g' > /tmp/config.json
sshix $ip "cd ~/dev/bridge47/bridge47-plugins/xapi && pm2 start xapi-router.js --name xapi -- --stack=${stack} --port=$(cat /tmp/config.json | jq -r '.routerPort')"

# ----- b47hq.mobilesebassist.net
curl -sS "http://$ip:12340/file/etc/nginx/sites-enabled/${hq_subd}.${domain_name}.conf" | egrep '# CONFIG_JSON ' | sed 's/^[^{[]*//g' > /tmp/config.json
sshix $ip "cd ~/dev/bridge47/bridge47-plugins/clientStart && pm2 start clientStart.js --name cstart -- --port=$(cat /tmp/config.json | jq -r '.routerPort')"

# ----------- start nginx ----------
sshix $ip "sudo nginx -t && sudo nginx"


