#!/bin/bash -e

#
# The final step is to startup the right services on the instance.
#
# * pm2 start various handlers:
#  * no-domain
#  * xapi
#
# * nginx
#

eval "$(cli-shezargs $@)"

[[ -z $ip     ]] && die "Need --ip="
[[ -z $color  ]] && die "Need --color="
[[ -z $stack  ]] && die "Need --stack="

if [[ $stack == test ]]; then
  domain_name="mobiledevassist.net"
elif [[ $stack == prod ]]; then
  domain_name="mobilewebassist.net"
fi

# ----- Nessus agent
if [[ $stack == prod ]]; then
  sshix $ip "cd ~/dev/bridge47/admin/build/on-instance/ && ./zz2-extra"
fi

# ----- no-domain
curl -sS "http://$ip:12340/file/etc/nginx/nginx.conf" | egrep '# CONFIG_JSON ' | sed 's/^[^{[]*//g' > /tmp/config.json
sshix $ip "cd ~/dev/bridge47/bridge47-plugins/no-domain/ && pm2 start no-domain.js -- port=$(cat /tmp/config.json | jq -r '.routerPort')"

#if [[ $stack != prod ]]; then
#  sshix $ip "cd ~/dev/bridge47/bridge47-plugins/echo/ && pm2 start echo.js -- --port=5790 --color=${color} --stack=${stack}"
#fi

# ----- color-test.mobilesebassist.net
curl -sS "http://$ip:12340/file/etc/nginx/sites-enabled/${color}-b47.${domain_name}.conf" | egrep '# CONFIG_JSON ' | sed 's/^[^{[]*//g' > /tmp/config.json
sshix $ip "cd ~/dev/bridge47/bridge47-plugins/xapi && pm2 start xapi-router.js --name xapi -- --stack=${stack} --port=$(cat /tmp/config.json | jq -r '.routerPort')"

# ----------- start nginx ----------
sshix $ip "sudo nginx -t && sudo nginx"


